spring.application.name=windows
server.port=8084
server.address=0.0.0.0


spring.datasource.url=jdbc:mysql://mysql-db:3306/myappdb?useSSL=false&allowPublicKeyRetrieval=true

spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



# server.port=5555
# = DATA SOURCE

# DATA SOURCE
# spring.datasource.url = jdbc:mysql://localhost:3306/junit?allowPublicKeyRetrieval=true&useSSL=false
# spring.datasource.url = jdbc:mysql://localhost:3306/junits?useSSL=false&createDatabaseIfNotExist=true

# spring.datasource.username = root
# spring.datasource.password = root

# JPA/Hibernate
